### ISSUE TITLE
是否可以设置透明背景

### ISSUE THREAD

**Issue by YYmmlin** [Davidyanlong/chartx3d#1]
问一下，图表中的白色背景是canvas默认的？还是3d渲染时默认的，是否可以不要背景颜色，设置成透明

**Comment by Davidyanlong** [comment]
![1595493560120](https://user-images.githubusercontent.com/10626549/88267355-51408400-cd03-11ea-8a00-fe82bc120694.jpg)
感谢使用，已修复！
